# Generated by Django 3.2.12 on 2023-10-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Listing',
        ),
    ]
